// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: message_flow.proto

package messageflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ContactNumber string                 `protobuf:"bytes,3,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`
	ContactName   string                 `protobuf:"bytes,4,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	LastMessageAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,6,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_message_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Conversation) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Conversation) GetContactNumber() string {
	if x != nil {
		return x.ContactNumber
	}
	return ""
}

func (x *Conversation) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Conversation) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *Conversation) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Sender         string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"` // "agent", "me", or contact JID
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,7,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	IsOutbound     bool                   `protobuf:"varint,8,opt,name=is_outbound,json=isOutbound,proto3" json:"is_outbound,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Message) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *Message) GetIsOutbound() bool {
	if x != nil {
		return x.IsOutbound
	}
	return false
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_message_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{2}
}

func (x *ListConversationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_message_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{3}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListConversationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Page           int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_message_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessagesRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetMessagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_message_flow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetMessagesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_message_flow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_message_flow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_message_flow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{8}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Event_MessageReceived
	//	*Event_MessageSent
	//	*Event_ConversationUpdated
	//	*Event_Presence
	Type          isEvent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_message_flow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetType() isEvent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Event) GetMessageReceived() *Message {
	if x != nil {
		if x, ok := x.Type.(*Event_MessageReceived); ok {
			return x.MessageReceived
		}
	}
	return nil
}

func (x *Event) GetMessageSent() *Message {
	if x != nil {
		if x, ok := x.Type.(*Event_MessageSent); ok {
			return x.MessageSent
		}
	}
	return nil
}

func (x *Event) GetConversationUpdated() *Conversation {
	if x != nil {
		if x, ok := x.Type.(*Event_ConversationUpdated); ok {
			return x.ConversationUpdated
		}
	}
	return nil
}

func (x *Event) GetPresence() *PresenceUpdate {
	if x != nil {
		if x, ok := x.Type.(*Event_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

type isEvent_Type interface {
	isEvent_Type()
}

type Event_MessageReceived struct {
	MessageReceived *Message `protobuf:"bytes,1,opt,name=message_received,json=messageReceived,proto3,oneof"`
}

type Event_MessageSent struct {
	MessageSent *Message `protobuf:"bytes,2,opt,name=message_sent,json=messageSent,proto3,oneof"`
}

type Event_ConversationUpdated struct {
	ConversationUpdated *Conversation `protobuf:"bytes,3,opt,name=conversation_updated,json=conversationUpdated,proto3,oneof"`
}

type Event_Presence struct {
	Presence *PresenceUpdate `protobuf:"bytes,4,opt,name=presence,proto3,oneof"`
}

func (*Event_MessageReceived) isEvent_Type() {}

func (*Event_MessageSent) isEvent_Type() {}

func (*Event_ConversationUpdated) isEvent_Type() {}

func (*Event_Presence) isEvent_Type() {}

type PresenceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlineUserIds []int64                `protobuf:"varint,1,rep,packed,name=online_user_ids,json=onlineUserIds,proto3" json:"online_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceUpdate) Reset() {
	*x = PresenceUpdate{}
	mi := &file_message_flow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdate) ProtoMessage() {}

func (x *PresenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_message_flow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdate.ProtoReflect.Descriptor instead.
func (*PresenceUpdate) Descriptor() ([]byte, []int) {
	return file_message_flow_proto_rawDescGZIP(), []int{10}
}

func (x *PresenceUpdate) GetOnlineUserIds() []int64 {
	if x != nil {
		return x.OnlineUserIds
	}
	return nil
}

var File_message_flow_proto protoreflect.FileDescriptor

const file_message_flow_proto_rawDesc = "" +
	"\n" +
	"\x12message_flow.proto\x12\x0emessageflow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12%\n" +
	"\x0econtact_number\x18\x03 \x01(\tR\rcontactNumber\x12!\n" +
	"\fcontact_name\x18\x04 \x01(\tR\vcontactName\x12B\n" +
	"\x0flast_message_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x12!\n" +
	"\funread_count\x18\x06 \x01(\x05R\vunreadCount\"\x91\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\rmetadata_json\x18\a \x01(\tR\fmetadataJson\x12\x1f\n" +
	"\vis_outbound\x18\b \x01(\bR\n" +
	"isOutbound\"D\n" +
	"\x18ListConversationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x94\x01\n" +
	"\x19ListConversationsResponse\x12B\n" +
	"\rconversations\x18\x01 \x03(\v2\x1c.messageflow.v1.ConversationR\rconversations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"g\n" +
	"\x12GetMessagesRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x7f\n" +
	"\x13GetMessagesResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.messageflow.v1.MessageR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"W\n" +
	"\x12SendMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"H\n" +
	"\x13SendMessageResponse\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.messageflow.v1.MessageR\amessage\"\x15\n" +
	"\x13StreamEventsRequest\"\xa4\x02\n" +
	"\x05Event\x12D\n" +
	"\x10message_received\x18\x01 \x01(\v2\x17.messageflow.v1.MessageH\x00R\x0fmessageReceived\x12<\n" +
	"\fmessage_sent\x18\x02 \x01(\v2\x17.messageflow.v1.MessageH\x00R\vmessageSent\x12Q\n" +
	"\x14conversation_updated\x18\x03 \x01(\v2\x1c.messageflow.v1.ConversationH\x00R\x13conversationUpdated\x12<\n" +
	"\bpresence\x18\x04 \x01(\v2\x1e.messageflow.v1.PresenceUpdateH\x00R\bpresenceB\x06\n" +
	"\x04type\"8\n" +
	"\x0ePresenceUpdate\x12&\n" +
	"\x0fonline_user_ids\x18\x01 \x03(\x03R\ronlineUserIds2\xf5\x02\n" +
	"\vChatService\x12h\n" +
	"\x11ListConversations\x12(.messageflow.v1.ListConversationsRequest\x1a).messageflow.v1.ListConversationsResponse\x12V\n" +
	"\vGetMessages\x12\".messageflow.v1.GetMessagesRequest\x1a#.messageflow.v1.GetMessagesResponse\x12V\n" +
	"\vSendMessage\x12\".messageflow.v1.SendMessageRequest\x1a#.messageflow.v1.SendMessageResponse\x12L\n" +
	"\fStreamEvents\x12#.messageflow.v1.StreamEventsRequest\x1a\x15.messageflow.v1.Event0\x01B1Z/message-flow/backend/pkg/proto/v1;messageflowv1b\x06proto3"

var (
	file_message_flow_proto_rawDescOnce sync.Once
	file_message_flow_proto_rawDescData []byte
)

func file_message_flow_proto_rawDescGZIP() []byte {
	file_message_flow_proto_rawDescOnce.Do(func() {
		file_message_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_flow_proto_rawDesc), len(file_message_flow_proto_rawDesc)))
	})
	return file_message_flow_proto_rawDescData
}

var file_message_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_message_flow_proto_goTypes = []any{
	(*Conversation)(nil),              // 0: messageflow.v1.Conversation
	(*Message)(nil),                   // 1: messageflow.v1.Message
	(*ListConversationsRequest)(nil),  // 2: messageflow.v1.ListConversationsRequest
	(*ListConversationsResponse)(nil), // 3: messageflow.v1.ListConversationsResponse
	(*GetMessagesRequest)(nil),        // 4: messageflow.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),       // 5: messageflow.v1.GetMessagesResponse
	(*SendMessageRequest)(nil),        // 6: messageflow.v1.SendMessageRequest
	(*SendMessageResponse)(nil),       // 7: messageflow.v1.SendMessageResponse
	(*StreamEventsRequest)(nil),       // 8: messageflow.v1.StreamEventsRequest
	(*Event)(nil),                     // 9: messageflow.v1.Event
	(*PresenceUpdate)(nil),            // 10: messageflow.v1.PresenceUpdate
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_message_flow_proto_depIdxs = []int32{
	11, // 0: messageflow.v1.Conversation.last_message_at:type_name -> google.protobuf.Timestamp
	11, // 1: messageflow.v1.Message.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: messageflow.v1.ListConversationsResponse.conversations:type_name -> messageflow.v1.Conversation
	1,  // 3: messageflow.v1.GetMessagesResponse.messages:type_name -> messageflow.v1.Message
	1,  // 4: messageflow.v1.SendMessageResponse.message:type_name -> messageflow.v1.Message
	1,  // 5: messageflow.v1.Event.message_received:type_name -> messageflow.v1.Message
	1,  // 6: messageflow.v1.Event.message_sent:type_name -> messageflow.v1.Message
	0,  // 7: messageflow.v1.Event.conversation_updated:type_name -> messageflow.v1.Conversation
	10, // 8: messageflow.v1.Event.presence:type_name -> messageflow.v1.PresenceUpdate
	2,  // 9: messageflow.v1.ChatService.ListConversations:input_type -> messageflow.v1.ListConversationsRequest
	4,  // 10: messageflow.v1.ChatService.GetMessages:input_type -> messageflow.v1.GetMessagesRequest
	6,  // 11: messageflow.v1.ChatService.SendMessage:input_type -> messageflow.v1.SendMessageRequest
	8,  // 12: messageflow.v1.ChatService.StreamEvents:input_type -> messageflow.v1.StreamEventsRequest
	3,  // 13: messageflow.v1.ChatService.ListConversations:output_type -> messageflow.v1.ListConversationsResponse
	5,  // 14: messageflow.v1.ChatService.GetMessages:output_type -> messageflow.v1.GetMessagesResponse
	7,  // 15: messageflow.v1.ChatService.SendMessage:output_type -> messageflow.v1.SendMessageResponse
	9,  // 16: messageflow.v1.ChatService.StreamEvents:output_type -> messageflow.v1.Event
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_message_flow_proto_init() }
func file_message_flow_proto_init() {
	if File_message_flow_proto != nil {
		return
	}
	file_message_flow_proto_msgTypes[9].OneofWrappers = []any{
		(*Event_MessageReceived)(nil),
		(*Event_MessageSent)(nil),
		(*Event_ConversationUpdated)(nil),
		(*Event_Presence)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_flow_proto_rawDesc), len(file_message_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_flow_proto_goTypes,
		DependencyIndexes: file_message_flow_proto_depIdxs,
		MessageInfos:      file_message_flow_proto_msgTypes,
	}.Build()
	File_message_flow_proto = out.File
	file_message_flow_proto_goTypes = nil
	file_message_flow_proto_depIdxs = nil
}
